---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "# jws-java-appdynamics\nbase build for any JWS application requiring\
      \ appdynamics agents\n"
    fabric8.jws-java-appdynamics/iconUrl: "img/icons/java.svg"
  labels: {}
  name: "jws-java-appdynamics"
objects:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    annotations: {}
    labels:
      app: "jws-java-appdynamics"
      project: "jws-java-appdynamics"
      version: "1.0.0-SNAPSHOT"
      group: "openshift"
    name: "jws-java-appdynamics"
  spec:
    dockerImageRepository: ""
    tags: []
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    annotations: {}
    labels:
      app: "jws-java-appdynamics"
      project: "jws-java-appdynamics"
      version: "1.0.0-SNAPSHOT"
      group: "openshift"
    name: "jws-java-appdynamics"
  spec:
    output:
      to:
        kind: "ImageStreamTag"
        name: "jws-java-appdynamics:1.1"
    source:
      contextDir: "src/main/docker"
      git:
        uri: "https://github.com/isanmartin0/jws-java-appdynamics"
      images: []
      secrets: []
      type: "Git"
    strategy:
      dockerStrategy:
        env: []
        from:
          kind: "ImageStreamTag"
#          name: "eap70-openshift:1.5"
          name: "webserver31-tomcat8-openshift:1.1"
          namespace: "openshift"
      type: "Docker"
    triggers:
    - imageChange:
        from:
          kind: "ImageStreamTag"
          name: "jws-java-appdynamics:1.1"
          namespace: "openshift"
      type: "ImageChange"
parameters: []
